---
title: "Benchmark data import"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(LANG = "en")
library(tidyverse)
library(lubridate)
library(readxl)



```

```{r}
df_bist=read_excel("bist100.xlsx")%>%head(-9)%>%select(1,2)%>%mutate(date=dmy(Tarih))%>%select(-Tarih)%>%rename(b_xu100=`TP MK F BILESIK`)%>%filter(is.na(b_xu100)==FALSE)%>%filter(is.na(date)==FALSE)%>%mutate(year=year(date), month=month(date))%>%group_by(year,month)%>%arrange(date)%>%summarise(data_date=max(date), b_xu100=last(b_xu100))%>%mutate(date=ymd(str_c(year,month,"1",sep="-")))%>%select(-year,-month)%>%glimpse()
```



```{r}
df_tufe=read_delim("tufe_raw.csv",  delim="|")%>%select(4,5,6)%>%tail(-1)%>%head(-1)%>%rename(b_tufe=Sütunlar, year=X4, month=X5)%>%fill(year)%>%separate(month,c("month_num","month_text"),sep="-")%>%unite("date_merge", year:month_num,sep="-")%>%mutate(date=ym(date_merge))%>%select(-month_text,-date_merge)%>%mutate(b_tufe=as.numeric(b_tufe))%>%glimpse()

```


```{r}
df_deposit=read_excel("deposit_interest_rates_monthly.xlsx")%>%mutate(date=ym(Tarih))%>%rename(b_deposit_rate=`TP TRY MT06`)%>%filter(is.na(date)==FALSE)%>%filter(is.na(b_deposit_rate)==FALSE)%>%select(date,b_deposit_rate)%>%glimpse()
```


```{r}
df_gold=read_excel("gold.xlsx")%>%filter(is.na(Tarih)==FALSE)%>%rename(date=Tarih, b_gold=Fiyat)%>%filter(is.na(b_gold)==FALSE)%>%mutate(year=year(date), month=month(date))%>%group_by(year,month)%>%arrange(date)%>%summarise(data_date=max(date), b_gold=last(b_gold))%>%mutate(date=ymd(str_c(year,month,"1",sep="-")))%>%select(-month,-year)%>%glimpse()
```


```{r}
df_property=read_excel("property_price_index.xlsx")%>%mutate(date=my(Tarih))%>%filter(is.na(date)==FALSE)%>%rename(b_property_index=`TP HKFE01`)%>%filter(is.na(b_property_index)==FALSE)%>%select(date,b_property_index)%>%mutate(b_property_index=as.numeric(b_property_index))%>%glimpse()
```




```{r}
df_usd=read_excel("usd_eur.xlsx")%>%rename(b_usd=`TP DK USD S YTL`)%>%mutate(date=dmy(Tarih))%>%filter(is.na(date)==FALSE)%>%filter(is.na(b_usd)==FALSE)%>%select(date,b_usd)%>%mutate(year=year(date), month=month(date))%>%group_by(year,month)%>%arrange(date)%>%summarise(data_date=max(date), b_usd=last(b_usd))%>%mutate(date=ymd(str_c(year,month,"1",sep="-")))%>%select(-year,-month)%>%glimpse()
```






```{r}
df_benchmark=full_join(df_bist,df_deposit,by="date")
df_benchmark=full_join(df_benchmark,df_gold,by="date")
df_benchmark=full_join(df_benchmark,df_property,by="date")
df_benchmark=full_join(df_benchmark,df_tufe,by="date")
df_benchmark=full_join(df_benchmark,df_usd,by="date")%>%arrange(date)%>%select(date,b_tufe,b_usd,b_gold, b_xu100,b_property_index,b_deposit_rate)%>%filter(date>=date("2015-11-01"))

df_benchmark
```


```{r}

```


```{r}
df_benchmark=df_benchmark%>%head(-2)
```

```{r}
df_benchmark_melt=df_benchmark%>%pivot_longer(cols=c(starts_with("b_")))%>%rename(price=value)%>%mutate(code=name, fund_type="benchmark",category="benchmark", company_code="benchmark", company_name="benchmark", OKS=FALSE, contribution=FALSE, participation=FALSE)

```


```{r}
write_rds(df_benchmark, "benchmark.rds")
write_rds(df_benchmark_melt, "benchmark_melt.rds")
```



